version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
