model: yolov5l-cls.pt
data: E:/Dataset/arthrosis_xray/PIP
epochs: 300
batch_size: 64
imgsz: 224
nosave: false
cache: null
device: ''
workers: 8
project: bone_age
name: PIP
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: bone_age\PIP
